# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Venv_projects/bist/package/bistUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_bistMain(object):
    def setupUi(self, bistMain):
        bistMain.setObjectName("bistMain")
        bistMain.resize(1900, 1010)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bistMain.sizePolicy().hasHeightForWidth())
        bistMain.setSizePolicy(sizePolicy)
        bistMain.setMinimumSize(QtCore.QSize(580, 750))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bistMain.setWindowIcon(icon)
        bistMain.setAutoFillBackground(False)
        bistMain.setStyleSheet("")
        bistMain.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(bistMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("font-size:18px;\n"
"background-color:#F2F2F2")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("border:none;font-size:25px; color:#0A5C9B")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.G = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 92, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.G.setPalette(palette)
        self.G.setStyleSheet("background:transparent;")
        self.G.setObjectName("G")
        self.widget = QtWidgets.QWidget(self.G)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1861, 941))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("border-radius: 50px 50px 0 50px;\n"
"background-color:#D9D9D9;")
        self.widget.setObjectName("widget")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(640, 10, 581, 111))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setStyleSheet("image:(\"../assets/images/exchange.png\");")
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.val_time = QtWidgets.QLabel(self.widget)
        self.val_time.setGeometry(QtCore.QRect(1650, 0, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_time.setFont(font)
        self.val_time.setStyleSheet("font-size:22px;border-radius: 50px 50px 0 0px;\n"
"background-color:gray;")
        self.val_time.setAlignment(QtCore.Qt.AlignCenter)
        self.val_time.setObjectName("val_time")
        self.val_date = QtWidgets.QLabel(self.widget)
        self.val_date.setGeometry(QtCore.QRect(0, 0, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_date.setFont(font)
        self.val_date.setStyleSheet("font-size:22px;border-radius: 50px 50px 0 0px;\n"
"background-color:gray;")
        self.val_date.setAlignment(QtCore.Qt.AlignCenter)
        self.val_date.setObjectName("val_date")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 140, 1821, 781))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.val_selling_btc = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_selling_btc.setFont(font)
        self.val_selling_btc.setStyleSheet("font-size:52px;")
        self.val_selling_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.val_selling_btc.setObjectName("val_selling_btc")
        self.gridLayout.addWidget(self.val_selling_btc, 4, 2, 1, 1)
        self.lbl_usd = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd.setFont(font)
        self.lbl_usd.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd.setObjectName("lbl_usd")
        self.gridLayout.addWidget(self.lbl_usd, 1, 0, 1, 1)
        self.val_buying_btc = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_buying_btc.setFont(font)
        self.val_buying_btc.setStyleSheet("font-size:52px;")
        self.val_buying_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.val_buying_btc.setObjectName("val_buying_btc")
        self.gridLayout.addWidget(self.val_buying_btc, 4, 1, 1, 1)
        self.val_selling_gbp = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_selling_gbp.setFont(font)
        self.val_selling_gbp.setStyleSheet("font-size:52px;")
        self.val_selling_gbp.setAlignment(QtCore.Qt.AlignCenter)
        self.val_selling_gbp.setObjectName("val_selling_gbp")
        self.gridLayout.addWidget(self.val_selling_gbp, 3, 2, 1, 1)
        self.val_buying_eth = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_buying_eth.setFont(font)
        self.val_buying_eth.setStyleSheet("font-size:52px;")
        self.val_buying_eth.setAlignment(QtCore.Qt.AlignCenter)
        self.val_buying_eth.setObjectName("val_buying_eth")
        self.gridLayout.addWidget(self.val_buying_eth, 5, 1, 1, 1)
        self.val_selling_usd = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_selling_usd.setFont(font)
        self.val_selling_usd.setStyleSheet("font-size:52px;")
        self.val_selling_usd.setAlignment(QtCore.Qt.AlignCenter)
        self.val_selling_usd.setObjectName("val_selling_usd")
        self.gridLayout.addWidget(self.val_selling_usd, 1, 2, 1, 1)
        self.val_buying_xu100 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_buying_xu100.setFont(font)
        self.val_buying_xu100.setStyleSheet("font-size:52px;")
        self.val_buying_xu100.setAlignment(QtCore.Qt.AlignCenter)
        self.val_buying_xu100.setObjectName("val_buying_xu100")
        self.gridLayout.addWidget(self.val_buying_xu100, 6, 1, 1, 1)
        self.val_selling_euro = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_selling_euro.setFont(font)
        self.val_selling_euro.setStyleSheet("font-size:52px;")
        self.val_selling_euro.setAlignment(QtCore.Qt.AlignCenter)
        self.val_selling_euro.setObjectName("val_selling_euro")
        self.gridLayout.addWidget(self.val_selling_euro, 2, 2, 1, 1)
        self.val_selling_eth = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_selling_eth.setFont(font)
        self.val_selling_eth.setStyleSheet("font-size:52px;")
        self.val_selling_eth.setAlignment(QtCore.Qt.AlignCenter)
        self.val_selling_eth.setObjectName("val_selling_eth")
        self.gridLayout.addWidget(self.val_selling_eth, 5, 2, 1, 1)
        self.lbl_gbp = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_gbp.setFont(font)
        self.lbl_gbp.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_gbp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gbp.setObjectName("lbl_gbp")
        self.gridLayout.addWidget(self.lbl_gbp, 3, 0, 1, 1)
        self.lbl_usd_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd_4.setFont(font)
        self.lbl_usd_4.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd_4.setObjectName("lbl_usd_4")
        self.gridLayout.addWidget(self.lbl_usd_4, 0, 0, 1, 1)
        self.val_buying_usd = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_buying_usd.setFont(font)
        self.val_buying_usd.setStyleSheet("font-size:52px;")
        self.val_buying_usd.setAlignment(QtCore.Qt.AlignCenter)
        self.val_buying_usd.setObjectName("val_buying_usd")
        self.gridLayout.addWidget(self.val_buying_usd, 1, 1, 1, 1)
        self.val_selling_xu100 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_selling_xu100.setFont(font)
        self.val_selling_xu100.setStyleSheet("font-size:52px;")
        self.val_selling_xu100.setAlignment(QtCore.Qt.AlignCenter)
        self.val_selling_xu100.setObjectName("val_selling_xu100")
        self.gridLayout.addWidget(self.val_selling_xu100, 6, 2, 1, 1)
        self.lbl_usd_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd_3.setFont(font)
        self.lbl_usd_3.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd_3.setObjectName("lbl_usd_3")
        self.gridLayout.addWidget(self.lbl_usd_3, 0, 1, 1, 1)
        self.val_change_usd = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_change_usd.setFont(font)
        self.val_change_usd.setStyleSheet("font-size:52px;")
        self.val_change_usd.setAlignment(QtCore.Qt.AlignCenter)
        self.val_change_usd.setObjectName("val_change_usd")
        self.gridLayout.addWidget(self.val_change_usd, 1, 3, 1, 1)
        self.lbl_usd_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd_5.setFont(font)
        self.lbl_usd_5.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd_5.setObjectName("lbl_usd_5")
        self.gridLayout.addWidget(self.lbl_usd_5, 0, 3, 1, 1)
        self.lbl_eth = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_eth.setFont(font)
        self.lbl_eth.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_eth.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eth.setObjectName("lbl_eth")
        self.gridLayout.addWidget(self.lbl_eth, 5, 0, 1, 1)
        self.val_change_euro = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_change_euro.setFont(font)
        self.val_change_euro.setStyleSheet("font-size:52px;")
        self.val_change_euro.setAlignment(QtCore.Qt.AlignCenter)
        self.val_change_euro.setObjectName("val_change_euro")
        self.gridLayout.addWidget(self.val_change_euro, 2, 3, 1, 1)
        self.lbl_btc = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_btc.setFont(font)
        self.lbl_btc.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_btc.setObjectName("lbl_btc")
        self.gridLayout.addWidget(self.lbl_btc, 4, 0, 1, 1)
        self.val_buying_euro = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_buying_euro.setFont(font)
        self.val_buying_euro.setStyleSheet("font-size:52px;")
        self.val_buying_euro.setAlignment(QtCore.Qt.AlignCenter)
        self.val_buying_euro.setObjectName("val_buying_euro")
        self.gridLayout.addWidget(self.val_buying_euro, 2, 1, 1, 1)
        self.val_change_btc = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_change_btc.setFont(font)
        self.val_change_btc.setStyleSheet("font-size:52px;")
        self.val_change_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.val_change_btc.setObjectName("val_change_btc")
        self.gridLayout.addWidget(self.val_change_btc, 4, 3, 1, 1)
        self.lbl_euro = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_euro.setFont(font)
        self.lbl_euro.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_euro.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_euro.setObjectName("lbl_euro")
        self.gridLayout.addWidget(self.lbl_euro, 2, 0, 1, 1)
        self.lbl_usd_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd_2.setFont(font)
        self.lbl_usd_2.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd_2.setObjectName("lbl_usd_2")
        self.gridLayout.addWidget(self.lbl_usd_2, 0, 2, 1, 1)
        self.val_change_eth = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_change_eth.setFont(font)
        self.val_change_eth.setStyleSheet("font-size:52px;")
        self.val_change_eth.setAlignment(QtCore.Qt.AlignCenter)
        self.val_change_eth.setObjectName("val_change_eth")
        self.gridLayout.addWidget(self.val_change_eth, 5, 3, 1, 1)
        self.val_change_gbp = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_change_gbp.setFont(font)
        self.val_change_gbp.setStyleSheet("font-size:52px;")
        self.val_change_gbp.setAlignment(QtCore.Qt.AlignCenter)
        self.val_change_gbp.setObjectName("val_change_gbp")
        self.gridLayout.addWidget(self.val_change_gbp, 3, 3, 1, 1)
        self.val_change_xu100 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_change_xu100.setFont(font)
        self.val_change_xu100.setStyleSheet("font-size:52px;")
        self.val_change_xu100.setAlignment(QtCore.Qt.AlignCenter)
        self.val_change_xu100.setObjectName("val_change_xu100")
        self.gridLayout.addWidget(self.val_change_xu100, 6, 3, 1, 1)
        self.lbl_xu100 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_xu100.setFont(font)
        self.lbl_xu100.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_xu100.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_xu100.setObjectName("lbl_xu100")
        self.gridLayout.addWidget(self.lbl_xu100, 6, 0, 1, 1)
        self.val_buying_gbp = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_buying_gbp.setFont(font)
        self.val_buying_gbp.setStyleSheet("font-size:52px;")
        self.val_buying_gbp.setAlignment(QtCore.Qt.AlignCenter)
        self.val_buying_gbp.setObjectName("val_buying_gbp")
        self.gridLayout.addWidget(self.val_buying_gbp, 3, 1, 1, 1)
        self.tabWidget.addTab(self.G, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(10, 20, 1861, 921))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("border-radius: 50px 50px 0 50px;\n"
"background-color:#D9D9D9;")
        self.widget_2.setObjectName("widget_2")
        self.combox_value = QtWidgets.QComboBox(self.widget_2)
        self.combox_value.setGeometry(QtCore.QRect(460, 100, 921, 101))
        self.combox_value.setStyleSheet("background:white;color:#0A5C9B;float:right;font-size:25px;border-radius: 25px;")
        self.combox_value.setObjectName("combox_value")
        self.combox_value.addItem("")
        self.combox_value.addItem("")
        self.combox_value.addItem("")
        self.combox_value.addItem("")
        self.combox_value.addItem("")
        self.combox_value.addItem("")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 300, 1711, 431))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.val_special_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_special_name.setFont(font)
        self.val_special_name.setStyleSheet("font-size:52px;background-color:gray;")
        self.val_special_name.setAlignment(QtCore.Qt.AlignCenter)
        self.val_special_name.setObjectName("val_special_name")
        self.gridLayout_2.addWidget(self.val_special_name, 1, 0, 1, 1)
        self.dfs = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dfs.setFont(font)
        self.dfs.setStyleSheet("font-size:52px;background-color:gray;")
        self.dfs.setAlignment(QtCore.Qt.AlignCenter)
        self.dfs.setObjectName("dfs")
        self.gridLayout_2.addWidget(self.dfs, 0, 3, 1, 1)
        self.lbl_usd_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd_10.setFont(font)
        self.lbl_usd_10.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd_10.setObjectName("lbl_usd_10")
        self.gridLayout_2.addWidget(self.lbl_usd_10, 0, 2, 1, 1)
        self.lbl_usd_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd_7.setFont(font)
        self.lbl_usd_7.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd_7.setObjectName("lbl_usd_7")
        self.gridLayout_2.addWidget(self.lbl_usd_7, 0, 0, 1, 1)
        self.val_special_buying = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_special_buying.setFont(font)
        self.val_special_buying.setStyleSheet("font-size:52px;")
        self.val_special_buying.setAlignment(QtCore.Qt.AlignCenter)
        self.val_special_buying.setObjectName("val_special_buying")
        self.gridLayout_2.addWidget(self.val_special_buying, 1, 1, 1, 1)
        self.val_special_selling = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_special_selling.setFont(font)
        self.val_special_selling.setStyleSheet("font-size:52px;")
        self.val_special_selling.setAlignment(QtCore.Qt.AlignCenter)
        self.val_special_selling.setObjectName("val_special_selling")
        self.gridLayout_2.addWidget(self.val_special_selling, 1, 2, 1, 1)
        self.val_special_change = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.val_special_change.setFont(font)
        self.val_special_change.setStyleSheet("font-size:52px;")
        self.val_special_change.setAlignment(QtCore.Qt.AlignCenter)
        self.val_special_change.setObjectName("val_special_change")
        self.gridLayout_2.addWidget(self.val_special_change, 1, 3, 1, 1)
        self.lbl_usd_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbl_usd_8.setFont(font)
        self.lbl_usd_8.setStyleSheet("font-size:52px;background-color:gray;")
        self.lbl_usd_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_usd_8.setObjectName("lbl_usd_8")
        self.gridLayout_2.addWidget(self.lbl_usd_8, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_3 = QtWidgets.QWidget(self.tab_5)
        self.widget_3.setGeometry(QtCore.QRect(10, 20, 1861, 921))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("border-radius: 50px 50px 0 50px;\n"
"background-color:#D9D9D9;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 40, 1861, 881))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.layout_news = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.layout_news.setContentsMargins(0, 0, 0, 0)
        self.layout_news.setObjectName("layout_news")
        self.btn_Refresh = QtWidgets.QPushButton(self.widget_3)
        self.btn_Refresh.setGeometry(QtCore.QRect(1620, 10, 161, 21))
        self.btn_Refresh.setObjectName("btn_Refresh")
        self.btn_Back = QtWidgets.QPushButton(self.widget_3)
        self.btn_Back.setGeometry(QtCore.QRect(70, 10, 161, 21))
        self.btn_Back.setObjectName("btn_Back")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        bistMain.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(bistMain)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(bistMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(bistMain)

    def retranslateUi(self, bistMain):
        _translate = QtCore.QCoreApplication.translate
        bistMain.setWindowTitle(_translate("bistMain", "EXCHANGE-TR"))
        self.val_time.setText(_translate("bistMain", "00:00:00"))
        self.val_date.setText(_translate("bistMain", "00:00:00"))
        self.val_selling_btc.setText(_translate("bistMain", "------"))
        self.lbl_usd.setText(_translate("bistMain", "USD/TRY:"))
        self.val_buying_btc.setText(_translate("bistMain", "------"))
        self.val_selling_gbp.setText(_translate("bistMain", "------"))
        self.val_buying_eth.setText(_translate("bistMain", "------"))
        self.val_selling_usd.setText(_translate("bistMain", "------"))
        self.val_buying_xu100.setText(_translate("bistMain", "------"))
        self.val_selling_euro.setText(_translate("bistMain", "------"))
        self.val_selling_eth.setText(_translate("bistMain", "------"))
        self.lbl_gbp.setText(_translate("bistMain", "GBP/TRY:"))
        self.lbl_usd_4.setText(_translate("bistMain", "NAME"))
        self.val_buying_usd.setText(_translate("bistMain", "-----"))
        self.val_selling_xu100.setText(_translate("bistMain", "------"))
        self.lbl_usd_3.setText(_translate("bistMain", "BUYING"))
        self.val_change_usd.setText(_translate("bistMain", "------"))
        self.lbl_usd_5.setText(_translate("bistMain", "CHANGE"))
        self.lbl_eth.setText(_translate("bistMain", "ETH/USD:"))
        self.val_change_euro.setText(_translate("bistMain", "------"))
        self.lbl_btc.setText(_translate("bistMain", "BTC/USD:"))
        self.val_buying_euro.setText(_translate("bistMain", "------"))
        self.val_change_btc.setText(_translate("bistMain", "------"))
        self.lbl_euro.setText(_translate("bistMain", "EUR/TRY:"))
        self.lbl_usd_2.setText(_translate("bistMain", "SELLING"))
        self.val_change_eth.setText(_translate("bistMain", "------"))
        self.val_change_gbp.setText(_translate("bistMain", "------"))
        self.val_change_xu100.setText(_translate("bistMain", "------"))
        self.lbl_xu100.setText(_translate("bistMain", "BIST100:"))
        self.val_buying_gbp.setText(_translate("bistMain", "------"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.G), _translate("bistMain", "WATCH ROOM"))
        self.combox_value.setItemText(0, _translate("bistMain", "USD/TRY"))
        self.combox_value.setItemText(1, _translate("bistMain", "EUR/TRY"))
        self.combox_value.setItemText(2, _translate("bistMain", "GBP/TRY"))
        self.combox_value.setItemText(3, _translate("bistMain", "BTC/TRY"))
        self.combox_value.setItemText(4, _translate("bistMain", "ETH/TRY"))
        self.combox_value.setItemText(5, _translate("bistMain", "XU100/TRY"))
        self.val_special_name.setText(_translate("bistMain", "----"))
        self.dfs.setText(_translate("bistMain", "CHANGE"))
        self.lbl_usd_10.setText(_translate("bistMain", "SELLING"))
        self.lbl_usd_7.setText(_translate("bistMain", "NAME"))
        self.val_special_buying.setText(_translate("bistMain", "-----"))
        self.val_special_selling.setText(_translate("bistMain", "------"))
        self.val_special_change.setText(_translate("bistMain", "------"))
        self.lbl_usd_8.setText(_translate("bistMain", "BUYING"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("bistMain", "SPECIAL VALUES"))
        self.btn_Refresh.setText(_translate("bistMain", "REFRESH"))
        self.btn_Back.setText(_translate("bistMain", "BACK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("bistMain", "NEWS"))
        self.actionExit.setText(_translate("bistMain", "Exit"))

